services:
  - type: worker
    name: stress-test-worker
    runtime: python
    plan: starter
    autoDeploy: false
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python stress-test.py"
    envVars:
      - key: PYTHONUNBUFFERED
        value: "TRUE"
